#ifndef LIBGWASPPCONFIG_H_
#define LIBGWASPPCONFIG_H_

#define LIBGWASPP_VERSION_MAJOR 0
#define LIBGWASPP_VERSION_MINOR 1
#define LIBGWASPP_VERSION_REVISION 0

#define COMPILE_LEVEL 0
#define DEBUG_LEVEL 1

#define COMPRESSION_LEVEL 3

#define PROCESSOR_WORD_SIZE 64
#endif
